version: '3.9'

services:
  web:
    build: .
    command: sh /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:17
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - .env.dev  
    ports:
      - "5432:5432"

volumes:
  postgres_data_dev:
