version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        gunicorn your_django_project.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: always

  db:
    image: postgres:17
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env.prod
    restart: always

volumes:
  postgres_data_prod:
