version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env.test
    depends_on:
      - db
    command: ["test"]

  db:
    image: postgres:17
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    env_file:
      - .env.test

volumes:
  postgres_data_test:
